package com.danny.dannys_ores.configs.ores.other;

import com.danny.dannys_ores.Main;
import net.minecraftforge.common.ForgeConfigSpec;
import net.minecraftforge.fml.ModLoadingContext;
import net.minecraftforge.fml.config.ModConfig;

import java.util.ArrayList;
import java.util.List;

public class Iridium {
    private static final ForgeConfigSpec.Builder BUILDER = new ForgeConfigSpec.Builder();
    public static ForgeConfigSpec spec;
    public static ForgeConfigSpec.BooleanValue disableIridiumOres;

    public static ForgeConfigSpec.BooleanValue enableStoneIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeStoneIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkStoneIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightStoneIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightStoneIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistStoneIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistStoneIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistStoneIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistStoneIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableAndesiteIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeAndesiteIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkAndesiteIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightAndesiteIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightAndesiteIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistAndesiteIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistAndesiteIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistAndesiteIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistAndesiteIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableDioriteIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeDioriteIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkDioriteIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightDioriteIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightDioriteIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistDioriteIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistDioriteIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistDioriteIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistDioriteIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableGraniteIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeGraniteIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkGraniteIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightGraniteIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightGraniteIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistGraniteIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistGraniteIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistGraniteIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistGraniteIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableNetherrackIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeNetherrackIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkNetherrackIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightNetherrackIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightNetherrackIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistNetherrackIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistNetherrackIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistNetherrackIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistNetherrackIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableEndStoneIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeEndStoneIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEndStoneIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightEndStoneIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightEndStoneIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEndStoneIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEndStoneIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEndStoneIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEndStoneIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableSandIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeSandIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkSandIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightSandIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightSandIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistSandIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistSandIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistSandIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistSandIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableRedSandIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeRedSandIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkRedSandIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightRedSandIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightRedSandIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistRedSandIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistRedSandIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistRedSandIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistRedSandIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableGravelIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeGravelIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkGravelIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightGravelIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightGravelIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistGravelIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistGravelIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistGravelIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistGravelIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableSandstoneIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeSandstoneIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkSandstoneIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightSandstoneIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightSandstoneIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistSandstoneIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistSandstoneIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistSandstoneIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistSandstoneIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableRedSandstoneIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeRedSandstoneIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkRedSandstoneIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightRedSandstoneIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightRedSandstoneIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistRedSandstoneIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistRedSandstoneIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistRedSandstoneIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistRedSandstoneIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableBlueIceIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeBlueIceIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkBlueIceIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightBlueIceIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightBlueIceIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistBlueIceIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistBlueIceIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistBlueIceIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistBlueIceIridiumOre;

    public static ForgeConfigSpec.BooleanValue enablePackedIceIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizePackedIceIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkPackedIceIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightPackedIceIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightPackedIceIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistPackedIceIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistPackedIceIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistPackedIceIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistPackedIceIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableBedrockIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeBedrockIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkBedrockIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightBedrockIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightBedrockIridiumOre;
    public static ForgeConfigSpec.DoubleValue resistanceBedrockIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistBedrockIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistBedrockIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistBedrockIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistBedrockIridiumOre;

    // Quark
    public static ForgeConfigSpec.BooleanValue enableQuarkBasaltIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkBasaltIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkBasaltIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkBasaltIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkBasaltIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkBasaltIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkBasaltIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkBasaltIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkBasaltIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkLimestoneIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkLimestoneIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkLimestoneIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkLimestoneIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkLimestoneIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkLimestoneIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkLimestoneIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkLimestoneIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkLimestoneIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkJasperIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkJasperIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkJasperIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkJasperIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkJasperIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkJasperIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkJasperIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkJasperIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkJasperIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkMarbleIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkMarbleIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkMarbleIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkMarbleIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkMarbleIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkMarbleIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkMarbleIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkMarbleIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkMarbleIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkSlateIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkSlateIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkSlateIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkSlateIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkSlateIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkSlateIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkSlateIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkSlateIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkSlateIridiumOre;

    // Embellishcraft
    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftBasaltIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftBasaltIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftBasaltIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftBasaltIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftBasaltIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftBasaltIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftBasaltIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftBasaltIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftBasaltIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftGneissIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftGneissIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftGneissIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftGneissIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftGneissIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftGneissIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftGneissIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftGneissIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftGneissIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftJadeIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftJadeIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftJadeIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftJadeIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftJadeIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftJadeIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftJadeIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftJadeIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftJadeIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftMarbleIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftMarbleIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftMarbleIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftMarbleIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftMarbleIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftMarbleIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftMarbleIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftMarbleIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftMarbleIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftLarvikiteIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftLarvikiteIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftLarvikiteIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftLarvikiteIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftLarvikiteIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftLarvikiteIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftLarvikiteIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftLarvikiteIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftLarvikiteIridiumOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftSlateIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftSlateIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftSlateIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftSlateIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftSlateIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftSlateIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftSlateIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftSlateIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftSlateIridiumOre;

    // Danny's Stone Variants
    public static ForgeConfigSpec.BooleanValue enableHardenedStoneIridiumOre;
    public static ForgeConfigSpec.IntValue veinSizeHardenedStoneIridiumOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkHardenedStoneIridiumOre;
    public static ForgeConfigSpec.IntValue minHeightHardenedStoneIridiumOre;
    public static ForgeConfigSpec.IntValue maxHeightHardenedStoneIridiumOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistHardenedStoneIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistHardenedStoneIridiumOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistHardenedStoneIridiumOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistHardenedStoneIridiumOre;

    static {
        // = BUILDER.comment("").define("", false);

        BUILDER.comment("Iridium Ores").push("general");
        disableIridiumOres = BUILDER.comment("If false, all iridium ore variants will be disabled.").define("disableAllVariants", false);
        BUILDER.comment("Stone Iridium Ore").push("stone_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableStoneIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeStoneIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkStoneIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightStoneIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightStoneIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistStoneIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistStoneIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistStoneIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistStoneIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Andesite Iridium Ore").push("andesite_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableAndesiteIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeAndesiteIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkAndesiteIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightAndesiteIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightAndesiteIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistAndesiteIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistAndesiteIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistAndesiteIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistAndesiteIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Diorite Iridium Ore").push("diorite_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableDioriteIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeDioriteIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkDioriteIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightDioriteIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightDioriteIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistDioriteIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistDioriteIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistDioriteIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistDioriteIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Granite Iridium Ore").push("granite_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableGraniteIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeGraniteIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkGraniteIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightGraniteIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightGraniteIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistGraniteIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistGraniteIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistGraniteIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistGraniteIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Netherrack Iridium Ore").push("netherrack_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableNetherrackIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeNetherrackIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkNetherrackIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightNetherrackIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 96, 0, 256);
        maxHeightNetherrackIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistNetherrackIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistNetherrackIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistNetherrackIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistNetherrackIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("End Stone Iridium Ore").push("end_stone_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEndStoneIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEndStoneIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkEndStoneIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightEndStoneIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEndStoneIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 24, 0, 256);
        isTempWhitelistEndStoneIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEndStoneIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEndStoneIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEndStoneIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Sand Iridium Ore").push("sand_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableSandIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeSandIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkSandIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightSandIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightSandIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistSandIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistSandIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistSandIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistSandIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Red Sand Iridium Ore").push("red_sand_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableRedSandIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeRedSandIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkRedSandIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightRedSandIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightRedSandIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistRedSandIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistRedSandIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistRedSandIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistRedSandIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Gravel Iridium Ore").push("gravel_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableGravelIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeGravelIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkGravelIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightGravelIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightGravelIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistGravelIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistGravelIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistGravelIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistGravelIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Sandstone Iridium Ore").push("sandstone_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableSandstoneIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeSandstoneIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkSandstoneIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightSandstoneIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightSandstoneIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistSandstoneIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistSandstoneIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistSandstoneIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistSandstoneIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Red Sandstone Iridium Ore").push("red_sandstone_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableRedSandstoneIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeRedSandstoneIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkRedSandstoneIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightRedSandstoneIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightRedSandstoneIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistRedSandstoneIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistRedSandstoneIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistRedSandstoneIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistRedSandstoneIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Blue Ice Iridium Ore").push("blue_ice_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableBlueIceIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeBlueIceIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkBlueIceIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightBlueIceIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightBlueIceIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistBlueIceIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistBlueIceIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistBlueIceIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistBlueIceIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Packed Ice Iridium Ore").push("packed_ice_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enablePackedIceIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizePackedIceIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkPackedIceIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightPackedIceIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightPackedIceIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistPackedIceIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistPackedIceIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistPackedIceIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistPackedIceIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Bedrock Iridium Ore").push("bedrock_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableBedrockIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeBedrockIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkBedrockIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 1, 0, 65536);
        minHeightBedrockIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightBedrockIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 256, 0, 256);
        isTempWhitelistBedrockIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistBedrockIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistBedrockIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistBedrockIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.comment("Block properties").push("properties");
        resistanceBedrockIridiumOre = BUILDER.comment("A higher value means a stronger explosion is needed to destroy this ore. Stone has 6.0 and Obsidian 1200.0").defineInRange("resistance", 9.0, 0.0, 3600000.0);
        BUILDER.pop();
        BUILDER.pop();

        //Quark
        BUILDER.comment("Basalt Iridium Ore (Quark)").push("quark_basalt_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkBasaltIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeQuarkBasaltIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkQuarkBasaltIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightQuarkBasaltIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 96, 0, 256);
        maxHeightQuarkBasaltIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistQuarkBasaltIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistQuarkBasaltIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistQuarkBasaltIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistQuarkBasaltIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Limestone Iridium Ore (Quark)").push("quark_limestone_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkLimestoneIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeQuarkLimestoneIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkQuarkLimestoneIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightQuarkLimestoneIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightQuarkLimestoneIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistQuarkLimestoneIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistQuarkLimestoneIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistQuarkLimestoneIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistQuarkLimestoneIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Jasper Iridium Ore (Quark)").push("quark_jasper_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkJasperIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeQuarkJasperIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkQuarkJasperIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightQuarkJasperIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightQuarkJasperIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistQuarkJasperIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistQuarkJasperIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistQuarkJasperIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistQuarkJasperIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Marble Iridium Ore (Quark)").push("quark_marble_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkMarbleIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeQuarkMarbleIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkQuarkMarbleIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightQuarkMarbleIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightQuarkMarbleIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistQuarkMarbleIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistQuarkMarbleIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistQuarkMarbleIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistQuarkMarbleIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Slate Iridium Ore (Quark)").push("quark_slate_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkSlateIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeQuarkSlateIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkQuarkSlateIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightQuarkSlateIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightQuarkSlateIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistQuarkSlateIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistQuarkSlateIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistQuarkSlateIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistQuarkSlateIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();

        //Embellishcraft
        BUILDER.comment("Basalt Iridium Ore (Embellishcraft)").push("embellishcraft_basalt_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftBasaltIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftBasaltIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkEmbellishcraftBasaltIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightEmbellishcraftBasaltIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftBasaltIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistEmbellishcraftBasaltIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftBasaltIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftBasaltIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftBasaltIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Gneiss Iridium Ore (Embellishcraft)").push("embellishcraft_gneiss_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftGneissIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftGneissIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkEmbellishcraftGneissIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightEmbellishcraftGneissIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftGneissIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistEmbellishcraftGneissIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftGneissIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftGneissIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftGneissIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Jade Iridium Ore (Embellishcraft)").push("embellishcraft_jade_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftJadeIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftJadeIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkEmbellishcraftJadeIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightEmbellishcraftJadeIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftJadeIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistEmbellishcraftJadeIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftJadeIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftJadeIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftJadeIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Larvikite Iridium Ore (Embellishcraft)").push("embellishcraft_larvikite_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftLarvikiteIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftLarvikiteIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkEmbellishcraftLarvikiteIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightEmbellishcraftLarvikiteIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftLarvikiteIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistEmbellishcraftLarvikiteIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftLarvikiteIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftLarvikiteIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftLarvikiteIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Marble Iridium Ore (Embellishcraft)").push("embellishcraft_marble_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftMarbleIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftMarbleIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkEmbellishcraftMarbleIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightEmbellishcraftMarbleIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftMarbleIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistEmbellishcraftMarbleIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftMarbleIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftMarbleIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftMarbleIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Slate Iridium Ore (Embellishcraft)").push("embellishcraft_slate_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftSlateIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftSlateIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkEmbellishcraftSlateIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightEmbellishcraftSlateIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftSlateIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistEmbellishcraftSlateIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftSlateIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftSlateIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftSlateIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();

        // Danny's Stone Variants
        BUILDER.comment("Hardened Stone Iridium Ore").push("hardened_stone_iridium_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableHardenedStoneIridiumOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeHardenedStoneIridiumOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkHardenedStoneIridiumOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk",1, 0, 65536);
        minHeightHardenedStoneIridiumOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightHardenedStoneIridiumOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistHardenedStoneIridiumOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistHardenedStoneIridiumOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistHardenedStoneIridiumOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistHardenedStoneIridiumOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.pop();
        spec = BUILDER.build();
        //BUILDER.comment("").push("");
        //
        //BUILDER.pop();
    }

    public static void loadConfig() {
        ModLoadingContext.get().registerConfig(ModConfig.Type.COMMON, Iridium.spec, Main.MOD_ID + "/iridium.toml");
    }
}
