package com.danny.dannys_ores.configs;

import com.danny.dannys_ores.Main;
import net.minecraftforge.common.ForgeConfigSpec;
import net.minecraftforge.fml.ModLoadingContext;
import net.minecraftforge.fml.config.ModConfig;

import java.util.ArrayList;
import java.util.List;

public class Coal {
    private static final ForgeConfigSpec.Builder BUILDER = new ForgeConfigSpec.Builder();
    public static ForgeConfigSpec spec;
    public static ForgeConfigSpec.BooleanValue enableCoalOres;

    public static ForgeConfigSpec.BooleanValue enableVanillaCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeVanillaCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkVanillaCoalOre;
    public static ForgeConfigSpec.IntValue minHeightVanillaCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightVanillaCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistVanillaCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistVanillaCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistVanillaCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistVanillaCoalOre;

    public static ForgeConfigSpec.BooleanValue enableAndesiteCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeAndesiteCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkAndesiteCoalOre;
    public static ForgeConfigSpec.IntValue minHeightAndesiteCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightAndesiteCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistAndesiteCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistAndesiteCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistAndesiteCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistAndesiteCoalOre;

    public static ForgeConfigSpec.BooleanValue enableDioriteCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeDioriteCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkDioriteCoalOre;
    public static ForgeConfigSpec.IntValue minHeightDioriteCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightDioriteCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistDioriteCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistDioriteCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistDioriteCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistDioriteCoalOre;

    public static ForgeConfigSpec.BooleanValue enableGraniteCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeGraniteCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkGraniteCoalOre;
    public static ForgeConfigSpec.IntValue minHeightGraniteCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightGraniteCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistGraniteCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistGraniteCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistGraniteCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistGraniteCoalOre;

    public static ForgeConfigSpec.BooleanValue enableNetherrackCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeNetherrackCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkNetherrackCoalOre;
    public static ForgeConfigSpec.IntValue minHeightNetherrackCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightNetherrackCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistNetherrackCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistNetherrackCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistNetherrackCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistNetherrackCoalOre;

    public static ForgeConfigSpec.BooleanValue enableEndStoneCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeEndStoneCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEndStoneCoalOre;
    public static ForgeConfigSpec.IntValue minHeightEndStoneCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightEndStoneCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEndStoneCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEndStoneCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEndStoneCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEndStoneCoalOre;

    public static ForgeConfigSpec.BooleanValue enableSandCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeSandCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkSandCoalOre;
    public static ForgeConfigSpec.IntValue minHeightSandCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightSandCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistSandCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistSandCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistSandCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistSandCoalOre;

    public static ForgeConfigSpec.BooleanValue enableRedSandCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeRedSandCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkRedSandCoalOre;
    public static ForgeConfigSpec.IntValue minHeightRedSandCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightRedSandCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistRedSandCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistRedSandCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistRedSandCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistRedSandCoalOre;

    public static ForgeConfigSpec.BooleanValue enableGravelCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeGravelCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkGravelCoalOre;
    public static ForgeConfigSpec.IntValue minHeightGravelCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightGravelCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistGravelCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistGravelCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistGravelCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistGravelCoalOre;

    public static ForgeConfigSpec.BooleanValue enableSandstoneCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeSandstoneCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkSandstoneCoalOre;
    public static ForgeConfigSpec.IntValue minHeightSandstoneCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightSandstoneCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistSandstoneCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistSandstoneCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistSandstoneCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistSandstoneCoalOre;

    public static ForgeConfigSpec.BooleanValue enableRedSandstoneCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeRedSandstoneCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkRedSandstoneCoalOre;
    public static ForgeConfigSpec.IntValue minHeightRedSandstoneCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightRedSandstoneCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistRedSandstoneCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistRedSandstoneCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistRedSandstoneCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistRedSandstoneCoalOre;

    public static ForgeConfigSpec.BooleanValue enableBedrockCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeBedrockCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkBedrockCoalOre;
    public static ForgeConfigSpec.IntValue minHeightBedrockCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightBedrockCoalOre;
    public static ForgeConfigSpec.DoubleValue resistanceBedrockCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistBedrockCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistBedrockCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistBedrockCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistBedrockCoalOre;

    // Quark
    public static ForgeConfigSpec.BooleanValue enableQuarkBasaltCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkBasaltCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkBasaltCoalOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkBasaltCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkBasaltCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkBasaltCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkBasaltCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkBasaltCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkBasaltCoalOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkLimestoneCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkLimestoneCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkLimestoneCoalOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkLimestoneCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkLimestoneCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkLimestoneCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkLimestoneCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkLimestoneCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkLimestoneCoalOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkJasperCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkJasperCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkJasperCoalOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkJasperCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkJasperCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkJasperCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkJasperCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkJasperCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkJasperCoalOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkMarbleCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkMarbleCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkMarbleCoalOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkMarbleCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkMarbleCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkMarbleCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkMarbleCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkMarbleCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkMarbleCoalOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkSlateCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkSlateCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkSlateCoalOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkSlateCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkSlateCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkSlateCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkSlateCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkSlateCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkSlateCoalOre;

    // Embellishcraft
    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftBasaltCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftBasaltCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftBasaltCoalOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftBasaltCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftBasaltCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftBasaltCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftBasaltCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftBasaltCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftBasaltCoalOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftGneissCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftGneissCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftGneissCoalOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftGneissCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftGneissCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftGneissCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftGneissCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftGneissCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftGneissCoalOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftJadeCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftJadeCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftJadeCoalOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftJadeCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftJadeCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftJadeCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftJadeCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftJadeCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftJadeCoalOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftMarbleCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftMarbleCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftMarbleCoalOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftMarbleCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftMarbleCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftMarbleCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftMarbleCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftMarbleCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftMarbleCoalOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftLarvikiteCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftLarvikiteCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftLarvikiteCoalOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftLarvikiteCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftLarvikiteCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftLarvikiteCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftLarvikiteCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftLarvikiteCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftLarvikiteCoalOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftSlateCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftSlateCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftSlateCoalOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftSlateCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftSlateCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftSlateCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftSlateCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftSlateCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftSlateCoalOre;

    // Danny's Stone Variants
    public static ForgeConfigSpec.BooleanValue enableHardenedStoneCoalOre;
    public static ForgeConfigSpec.IntValue veinSizeHardenedStoneCoalOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkHardenedStoneCoalOre;
    public static ForgeConfigSpec.IntValue minHeightHardenedStoneCoalOre;
    public static ForgeConfigSpec.IntValue maxHeightHardenedStoneCoalOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistHardenedStoneCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistHardenedStoneCoalOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistHardenedStoneCoalOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistHardenedStoneCoalOre;

    static {
        // = BUILDER.comment("").define("", false);

        BUILDER.comment("Coal Ores").push("coal_ores");
        enableCoalOres = BUILDER.comment("Enable or disable all Coal Ore variants.").define("enableCoalOres", true);
        BUILDER.comment("Vanilla (Stone) Coal Ore").push("vanilla_stone_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableVanillaCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVanillaCoalOre", true);
        veinSizeVanillaCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeVanillaCoalOre", 17, 0, 65536);
        veinsPerChunkVanillaCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkVanillaCoalOre", 20, 0, 65536);
        minHeightVanillaCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightVanillaCoalOre", 0, 0, 256);
        maxHeightVanillaCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightVanillaCoalOre", 128, 0, 256);
        isTempWhitelistVanillaCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistVanillaCoalOre", false);
        temperatureBlacklistVanillaCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistVanillaCoalOre", new ArrayList<String>());
        isBiomeWhitelistVanillaCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistVanillaCoalOre", false);
        biomeBlacklistVanillaCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklistVanillaCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Andesite Coal Ore").push("andesite_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableAndesiteCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableAndesiteCoalOre", true);
        veinSizeAndesiteCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeAndesiteCoalOre", 17, 0, 65536);
        veinsPerChunkAndesiteCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkAndesiteCoalOre", 20, 0, 65536);
        minHeightAndesiteCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightAndesiteCoalOre", 0, 0, 256);
        maxHeightAndesiteCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightAndesiteCoalOre", 128, 0, 256);
        isTempWhitelistAndesiteCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistAndesiteCoalOre", false);
        temperatureBlacklistAndesiteCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistAndesiteCoalOre", new ArrayList<String>());
        isBiomeWhitelistAndesiteCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistAndesiteCoalOre", false);
        biomeBlacklistAndesiteCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklistAndesiteCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Diorite Coal Ore").push("diorite_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableDioriteCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableDioriteCoalOre", true);
        veinSizeDioriteCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeDioriteCoalOre", 17, 0, 65536);
        veinsPerChunkDioriteCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkDioriteCoalOre", 20, 0, 65536);
        minHeightDioriteCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightDioriteCoalOre", 0, 0, 256);
        maxHeightDioriteCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightDioriteCoalOre", 128, 0, 256);
        isTempWhitelistDioriteCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistDioriteCoalOre", false);
        temperatureBlacklistDioriteCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistDioriteCoalOre", new ArrayList<String>());
        isBiomeWhitelistDioriteCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistDioriteCoalOre", false);
        biomeBlacklistDioriteCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklistDioriteCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Granite Coal Ore").push("granite_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableGraniteCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableGraniteCoalOre", true);
        veinSizeGraniteCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeGraniteCoalOre", 17, 0, 65536);
        veinsPerChunkGraniteCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkGraniteCoalOre", 20, 0, 65536);
        minHeightGraniteCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightGraniteCoalOre", 0, 0, 256);
        maxHeightGraniteCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightGraniteCoalOre", 128, 0, 256);
        isTempWhitelistGraniteCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistGraniteCoalOre", false);
        temperatureBlacklistGraniteCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistGraniteCoalOre", new ArrayList<String>());
        isBiomeWhitelistGraniteCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistGraniteCoalOre", false);
        biomeBlacklistGraniteCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklistGraniteCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Netherrack Coal Ore").push("netherrack_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableNetherrackCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableNetherrackCoalOre", true);
        veinSizeNetherrackCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeNetherrackCoalOre", 17, 0, 65536);
        veinsPerChunkNetherrackCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkNetherrackCoalOre", 20, 0, 65536);
        minHeightNetherrackCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightNetherrackCoalOre", 10, 0, 256);
        maxHeightNetherrackCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightNetherrackCoalOre", 128, 0, 256);
        isTempWhitelistNetherrackCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistNetherrackCoalOre", false);
        temperatureBlacklistNetherrackCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistNetherrackCoalOre", new ArrayList<String>());
        isBiomeWhitelistNetherrackCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistNetherrackCoalOre", false);
        biomeBlacklistNetherrackCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklistNetherrackCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("End Stone Coal Ore").push("end_stone_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEndStoneCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableEndStoneCoalOre", true);
        veinSizeEndStoneCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeEndStoneCoalOre", 8, 0, 65536);
        veinsPerChunkEndStoneCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkEndStoneCoalOre", 10, 0, 65536);
        minHeightEndStoneCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightEndStoneCoalOre", 10, 0, 256);
        maxHeightEndStoneCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightEndStoneCoalOre", 128, 0, 256);
        isTempWhitelistEndStoneCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistEndStoneCoalOre", false);
        temperatureBlacklistEndStoneCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistEndStoneCoalOre", new ArrayList<String>());
        isBiomeWhitelistEndStoneCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistEndStoneCoalOre", false);
        biomeBlacklistEndStoneCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklistEndStoneCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Sand Coal Ore").push("sand_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableSandCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableSandCoalOre", true);
        veinSizeSandCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeSandCoalOre", 8, 0, 65536);
        veinsPerChunkSandCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkSandCoalOre", 10, 0, 65536);
        minHeightSandCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightSandCoalOre", 0, 0, 256);
        maxHeightSandCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightSandCoalOre", 128, 0, 256);
        isTempWhitelistSandCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistSandCoalOre", false);
        temperatureBlacklistSandCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistSandCoalOre", new ArrayList<String>());
        isBiomeWhitelistSandCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistSandCoalOre", false);
        biomeBlacklistSandCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklistSandCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Red Sand Coal Ore").push("red_sand_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableRedSandCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableRedSandCoalOre", true);
        veinSizeRedSandCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeRedSandCoalOre", 8, 0, 65536);
        veinsPerChunkRedSandCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkRedSandCoalOre", 10, 0, 65536);
        minHeightRedSandCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightRedSandCoalOre", 0, 0, 256);
        maxHeightRedSandCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightRedSandCoalOre", 128, 0, 256);
        isTempWhitelistRedSandCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistRedSandCoalOre", false);
        temperatureBlacklistRedSandCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistRedSandCoalOre", new ArrayList<String>());
        isBiomeWhitelistRedSandCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistRedSandCoalOre", false);
        biomeBlacklistRedSandCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklistRedSandCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Gravel Coal Ore").push("gravel_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableGravelCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableGravelCoalOre", true);
        veinSizeGravelCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeGravelCoalOre", 8, 0, 65536);
        veinsPerChunkGravelCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkGravelCoalOre", 10, 0, 65536);
        minHeightGravelCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightGravelCoalOre", 0, 0, 256);
        maxHeightGravelCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightGravelCoalOre", 128, 0, 256);
        isTempWhitelistGravelCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistGravelCoalOre", false);
        temperatureBlacklistGravelCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistGravelCoalOre", new ArrayList<String>());
        isBiomeWhitelistGravelCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistGravelCoalOre", false);
        biomeBlacklistGravelCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklistGravelCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Sandstone Coal Ore").push("sandstone_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableSandstoneCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableSandstoneCoalOre", true);
        veinSizeSandstoneCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeSandstoneCoalOre", 8, 0, 65536);
        veinsPerChunkSandstoneCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkSandstoneCoalOre", 10, 0, 65536);
        minHeightSandstoneCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightSandstoneCoalOre", 0, 0, 256);
        maxHeightSandstoneCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightSandstoneCoalOre", 128, 0, 256);
        isTempWhitelistSandstoneCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistSandstoneCoalOre", false);
        temperatureBlacklistSandstoneCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistSandstoneCoalOre", new ArrayList<String>());
        isBiomeWhitelistSandstoneCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistSandstoneCoalOre", false);
        biomeBlacklistSandstoneCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklistSandstoneCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Red Sandstone Coal Ore").push("red_sandstone_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableRedSandstoneCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableRedSandstoneCoalOre", true);
        veinSizeRedSandstoneCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeRedSandstoneCoalOre", 8, 0, 65536);
        veinsPerChunkRedSandstoneCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkRedSandstoneCoalOre", 10, 0, 65536);
        minHeightRedSandstoneCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightRedSandstoneCoalOre", 0, 0, 256);
        maxHeightRedSandstoneCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightRedSandstoneCoalOre", 128, 0, 256);
        isTempWhitelistRedSandstoneCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistRedSandstoneCoalOre", false);
        temperatureBlacklistRedSandstoneCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistRedSandstoneCoalOre", new ArrayList<String>());
        isBiomeWhitelistRedSandstoneCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistRedSandstoneCoalOre", false);
        biomeBlacklistRedSandstoneCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklistRedSandstoneCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Bedrock Coal Ore").push("bedrock_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableBedrockCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableBedrockCoalOre", true);
        veinSizeBedrockCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeBedrockCoalOre", 1, 0, 65536);
        veinsPerChunkBedrockCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkBedrockCoalOre", 1, 0, 65536);
        minHeightBedrockCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightBedrockCoalOre", 0, 0, 256);
        maxHeightBedrockCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightBedrockCoalOre", 256, 0, 256);
        isTempWhitelistBedrockCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistBedrockCoalOre", false);
        temperatureBlacklistBedrockCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistBedrockCoalOre", new ArrayList<String>());
        isBiomeWhitelistBedrockCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistBedrockCoalOre", false);
        biomeBlacklistBedrockCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklistBedrockCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.comment("Block properties").push("properties");
        resistanceBedrockCoalOre = BUILDER.comment("A higher value means a stronger explosion is needed to destroy this ore. Stone has 6.0 and Obsidian 1200.0").defineInRange("resistanceBedrockCoalOre", 9.0, 0.0, 3600000.0);
        BUILDER.pop();
        BUILDER.pop();

        //Quark
        BUILDER.comment("Basalt Coal Ore (Quark)").push("quark_basalt_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkBasaltCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableQuarkBasaltCoalOre", true);
        veinSizeQuarkBasaltCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeQuarkBasaltCoalOre", 17, 0, 65536);
        veinsPerChunkQuarkBasaltCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkQuarkBasaltCoalOre", 20, 0, 65536);
        minHeightQuarkBasaltCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightQuarkBasaltCoalOre", 10, 0, 256);
        maxHeightQuarkBasaltCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightQuarkBasaltCoalOre", 128, 0, 256);
        isTempWhitelistQuarkBasaltCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistQuarkBasaltCoalOre", false);
        temperatureBlacklistQuarkBasaltCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistQuarkBasaltCoalOre", new ArrayList<String>());
        isBiomeWhitelistQuarkBasaltCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistQuarkBasaltCoalOre", false);
        biomeBlacklistQuarkBasaltCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklistQuarkBasaltCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Limestone Coal Ore (Quark)").push("quark_limestone_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkLimestoneCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableQuarkLimestoneCoalOre", true);
        veinSizeQuarkLimestoneCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeQuarkLimestoneCoalOre", 17, 0, 65536);
        veinsPerChunkQuarkLimestoneCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkQuarkLimestoneCoalOre", 20, 0, 65536);
        minHeightQuarkLimestoneCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightQuarkLimestoneCoalOre", 0, 0, 256);
        maxHeightQuarkLimestoneCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightQuarkLimestoneCoalOre", 128, 0, 256);
        isTempWhitelistQuarkLimestoneCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistQuarkLimestoneCoalOre", false);
        temperatureBlacklistQuarkLimestoneCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistQuarkLimestoneCoalOre", new ArrayList<String>());
        isBiomeWhitelistQuarkLimestoneCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistQuarkLimestoneCoalOre", false);
        biomeBlacklistQuarkLimestoneCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklistQuarkLimestoneCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Jasper Coal Ore (Quark)").push("quark_jasper_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkJasperCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableQuarkJasperCoalOre", true);
        veinSizeQuarkJasperCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeQuarkJasperCoalOre", 17, 0, 65536);
        veinsPerChunkQuarkJasperCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkQuarkJasperCoalOre", 20, 0, 65536);
        minHeightQuarkJasperCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightQuarkJasperCoalOre", 0, 0, 256);
        maxHeightQuarkJasperCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightQuarkJasperCoalOre", 128, 0, 256);
        isTempWhitelistQuarkJasperCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistQuarkJasperCoalOre", false);
        temperatureBlacklistQuarkJasperCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistQuarkJasperCoalOre", new ArrayList<String>());
        isBiomeWhitelistQuarkJasperCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistQuarkJasperCoalOre", false);
        biomeBlacklistQuarkJasperCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklistQuarkJasperCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Marble Coal Ore (Quark)").push("quark_marble_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkMarbleCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableQuarkMarbleCoalOre", true);
        veinSizeQuarkMarbleCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeQuarkMarbleCoalOre", 17, 0, 65536);
        veinsPerChunkQuarkMarbleCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkQuarkMarbleCoalOre", 20, 0, 65536);
        minHeightQuarkMarbleCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightQuarkMarbleCoalOre", 0, 0, 256);
        maxHeightQuarkMarbleCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightQuarkMarbleCoalOre", 128, 0, 256);
        isTempWhitelistQuarkMarbleCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistQuarkMarbleCoalOre", false);
        temperatureBlacklistQuarkMarbleCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistQuarkMarbleCoalOre", new ArrayList<String>());
        isBiomeWhitelistQuarkMarbleCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistQuarkMarbleCoalOre", false);
        biomeBlacklistQuarkMarbleCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklistQuarkMarbleCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Slate Coal Ore (Quark)").push("quark_slate_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkSlateCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableQuarkSlateCoalOre", true);
        veinSizeQuarkSlateCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeQuarkSlateCoalOre", 17, 0, 65536);
        veinsPerChunkQuarkSlateCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkQuarkSlateCoalOre", 20, 0, 65536);
        minHeightQuarkSlateCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightQuarkSlateCoalOre", 0, 0, 256);
        maxHeightQuarkSlateCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightQuarkSlateCoalOre", 128, 0, 256);
        isTempWhitelistQuarkSlateCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistQuarkSlateCoalOre", false);
        temperatureBlacklistQuarkSlateCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistQuarkSlateCoalOre", new ArrayList<String>());
        isBiomeWhitelistQuarkSlateCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistQuarkSlateCoalOre", false);
        biomeBlacklistQuarkSlateCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklistQuarkSlateCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();

        //Embellishcraft
        BUILDER.comment("Basalt Coal Ore (Embellishcraft)").push("embellishcraft_basalt_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftBasaltCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableEmbellishcraftBasaltCoalOre", true);
        veinSizeEmbellishcraftBasaltCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeEmbellishcraftBasaltCoalOre", 17, 0, 65536);
        veinsPerChunkEmbellishcraftBasaltCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkEmbellishcraftBasaltCoalOre", 20, 0, 65536);
        minHeightEmbellishcraftBasaltCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightEmbellishcraftBasaltCoalOre", 0, 0, 256);
        maxHeightEmbellishcraftBasaltCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightEmbellishcraftBasaltCoalOre", 128, 0, 256);
        isTempWhitelistEmbellishcraftBasaltCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistEmbellishcraftBasaltCoalOre", false);
        temperatureBlacklistEmbellishcraftBasaltCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistEmbellishcraftBasaltCoalOre", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftBasaltCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistEmbellishcraftBasaltCoalOre", false);
        biomeBlacklistEmbellishcraftBasaltCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklistEmbellishcraftBasaltCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Gneiss Coal Ore (Embellishcraft)").push("embellishcraft_gneiss_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftGneissCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableEmbellishcraftGneissCoalOre", true);
        veinSizeEmbellishcraftGneissCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeEmbellishcraftGneissCoalOre", 17, 0, 65536);
        veinsPerChunkEmbellishcraftGneissCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkEmbellishcraftGneissCoalOre", 20, 0, 65536);
        minHeightEmbellishcraftGneissCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightEmbellishcraftGneissCoalOre", 0, 0, 256);
        maxHeightEmbellishcraftGneissCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightEmbellishcraftGneissCoalOre", 128, 0, 256);
        isTempWhitelistEmbellishcraftGneissCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistEmbellishcraftGneissCoalOre", false);
        temperatureBlacklistEmbellishcraftGneissCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistEmbellishcraftGneissCoalOre", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftGneissCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistEmbellishcraftGneissCoalOre", false);
        biomeBlacklistEmbellishcraftGneissCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklistEmbellishcraftGneissCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Jade Coal Ore (Embellishcraft)").push("embellishcraft_jade_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftJadeCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableEmbellishcraftJadeCoalOre", true);
        veinSizeEmbellishcraftJadeCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeEmbellishcraftJadeCoalOre", 17, 0, 65536);
        veinsPerChunkEmbellishcraftJadeCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkEmbellishcraftJadeCoalOre", 20, 0, 65536);
        minHeightEmbellishcraftJadeCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightEmbellishcraftJadeCoalOre", 0, 0, 256);
        maxHeightEmbellishcraftJadeCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightEmbellishcraftJadeCoalOre", 128, 0, 256);
        isTempWhitelistEmbellishcraftJadeCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistEmbellishcraftJadeCoalOre", false);
        temperatureBlacklistEmbellishcraftJadeCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistEmbellishcraftJadeCoalOre", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftJadeCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistEmbellishcraftJadeCoalOre", false);
        biomeBlacklistEmbellishcraftJadeCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklistEmbellishcraftJadeCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Larvikite Coal Ore (Embellishcraft)").push("embellishcraft_larvikite_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftLarvikiteCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableEmbellishcraftLarvikiteCoalOre", true);
        veinSizeEmbellishcraftLarvikiteCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeEmbellishcraftLarvikiteCoalOre", 17, 0, 65536);
        veinsPerChunkEmbellishcraftLarvikiteCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkEmbellishcraftLarvikiteCoalOre", 20, 0, 65536);
        minHeightEmbellishcraftLarvikiteCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightEmbellishcraftLarvikiteCoalOre", 0, 0, 256);
        maxHeightEmbellishcraftLarvikiteCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightEmbellishcraftLarvikiteCoalOre", 128, 0, 256);
        isTempWhitelistEmbellishcraftLarvikiteCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistEmbellishcraftLarvikiteCoalOre", false);
        temperatureBlacklistEmbellishcraftLarvikiteCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistEmbellishcraftLarvikiteCoalOre", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftLarvikiteCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistEmbellishcraftLarvikiteCoalOre", false);
        biomeBlacklistEmbellishcraftLarvikiteCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklistEmbellishcraftLarvikiteCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Marble Coal Ore (Embellishcraft)").push("embellishcraft_marble_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftMarbleCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableEmbellishcraftMarbleCoalOre", true);
        veinSizeEmbellishcraftMarbleCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeEmbellishcraftMarbleCoalOre", 17, 0, 65536);
        veinsPerChunkEmbellishcraftMarbleCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkEmbellishcraftMarbleCoalOre", 20, 0, 65536);
        minHeightEmbellishcraftMarbleCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightEmbellishcraftMarbleCoalOre", 0, 0, 256);
        maxHeightEmbellishcraftMarbleCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightEmbellishcraftMarbleCoalOre", 128, 0, 256);
        isTempWhitelistEmbellishcraftMarbleCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistEmbellishcraftMarbleCoalOre", false);
        temperatureBlacklistEmbellishcraftMarbleCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistEmbellishcraftMarbleCoalOre", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftMarbleCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistEmbellishcraftMarbleCoalOre", false);
        biomeBlacklistEmbellishcraftMarbleCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklistEmbellishcraftMarbleCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Slate Coal Ore (Embellishcraft)").push("embellishcraft_slate_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftSlateCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableEmbellishcraftSlateCoalOre", true);
        veinSizeEmbellishcraftSlateCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeEmbellishcraftSlateCoalOre", 17, 0, 65536);
        veinsPerChunkEmbellishcraftSlateCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkEmbellishcraftSlateCoalOre", 20, 0, 65536);
        minHeightEmbellishcraftSlateCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightEmbellishcraftSlateCoalOre", 0, 0, 256);
        maxHeightEmbellishcraftSlateCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightEmbellishcraftSlateCoalOre", 128, 0, 256);
        isTempWhitelistEmbellishcraftSlateCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistEmbellishcraftSlateCoalOre", false);
        temperatureBlacklistEmbellishcraftSlateCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistEmbellishcraftSlateCoalOre", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftSlateCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistEmbellishcraftSlateCoalOre", false);
        biomeBlacklistEmbellishcraftSlateCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklistEmbellishcraftSlateCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();

        // Danny's Stone Variants
        BUILDER.comment("Hardened Stone Coal Ore").push("hardened_stone_coal_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableHardenedStoneCoalOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableHardenedStoneCoalOre", true);
        veinSizeHardenedStoneCoalOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSizeHardenedStoneCoalOre", 17, 0, 65536);
        veinsPerChunkHardenedStoneCoalOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunkHardenedStoneCoalOre", 20, 0, 65536);
        minHeightHardenedStoneCoalOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeightHardenedStoneCoalOre", 0, 0, 256);
        maxHeightHardenedStoneCoalOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeightHardenedStoneCoalOre", 128, 0, 256);
        isTempWhitelistHardenedStoneCoalOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelistHardenedStoneCoalOre", false);
        temperatureBlacklistHardenedStoneCoalOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklistHardenedStoneCoalOre", new ArrayList<String>());
        isBiomeWhitelistHardenedStoneCoalOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelistHardenedStoneCoalOre", false);
        biomeBlacklistHardenedStoneCoalOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklistHardenedStoneCoalOre", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.pop();
        spec = BUILDER.build();
        //BUILDER.comment("").push("");
        //
        //BUILDER.pop();
    }

    public static void loadConfig() {
        ModLoadingContext.get().registerConfig(ModConfig.Type.COMMON, Coal.spec, Main.MOD_ID + "/coal.toml");
    }
}
