package com.danny.dannys_ores.configs.ores;

import com.danny.dannys_ores.Main;
import net.minecraftforge.common.ForgeConfigSpec;
import net.minecraftforge.fml.ModLoadingContext;
import net.minecraftforge.fml.config.ModConfig;

import java.util.ArrayList;
import java.util.List;

public class Cobalt {
    private static final ForgeConfigSpec.Builder BUILDER = new ForgeConfigSpec.Builder();
    public static ForgeConfigSpec spec;
    public static ForgeConfigSpec.BooleanValue disableCobaltOres;

    public static ForgeConfigSpec.BooleanValue enableStoneCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeStoneCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkStoneCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightStoneCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightStoneCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistStoneCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistStoneCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistStoneCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistStoneCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableAndesiteCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeAndesiteCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkAndesiteCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightAndesiteCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightAndesiteCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistAndesiteCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistAndesiteCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistAndesiteCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistAndesiteCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableDioriteCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeDioriteCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkDioriteCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightDioriteCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightDioriteCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistDioriteCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistDioriteCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistDioriteCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistDioriteCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableGraniteCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeGraniteCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkGraniteCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightGraniteCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightGraniteCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistGraniteCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistGraniteCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistGraniteCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistGraniteCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableNetherrackCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeNetherrackCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkNetherrackCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightNetherrackCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightNetherrackCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistNetherrackCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistNetherrackCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistNetherrackCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistNetherrackCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableEndStoneCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeEndStoneCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEndStoneCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightEndStoneCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightEndStoneCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEndStoneCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEndStoneCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEndStoneCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEndStoneCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableSandCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeSandCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkSandCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightSandCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightSandCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistSandCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistSandCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistSandCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistSandCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableRedSandCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeRedSandCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkRedSandCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightRedSandCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightRedSandCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistRedSandCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistRedSandCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistRedSandCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistRedSandCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableGravelCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeGravelCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkGravelCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightGravelCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightGravelCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistGravelCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistGravelCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistGravelCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistGravelCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableSandstoneCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeSandstoneCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkSandstoneCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightSandstoneCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightSandstoneCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistSandstoneCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistSandstoneCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistSandstoneCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistSandstoneCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableRedSandstoneCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeRedSandstoneCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkRedSandstoneCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightRedSandstoneCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightRedSandstoneCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistRedSandstoneCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistRedSandstoneCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistRedSandstoneCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistRedSandstoneCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableBlueIceCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeBlueIceCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkBlueIceCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightBlueIceCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightBlueIceCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistBlueIceCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistBlueIceCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistBlueIceCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistBlueIceCobaltOre;

    public static ForgeConfigSpec.BooleanValue enablePackedIceCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizePackedIceCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkPackedIceCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightPackedIceCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightPackedIceCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistPackedIceCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistPackedIceCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistPackedIceCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistPackedIceCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableBedrockCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeBedrockCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkBedrockCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightBedrockCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightBedrockCobaltOre;
    public static ForgeConfigSpec.DoubleValue resistanceBedrockCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistBedrockCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistBedrockCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistBedrockCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistBedrockCobaltOre;

    // Quark
    public static ForgeConfigSpec.BooleanValue enableQuarkBasaltCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkBasaltCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkBasaltCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkBasaltCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkBasaltCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkBasaltCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkBasaltCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkBasaltCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkBasaltCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkLimestoneCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkLimestoneCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkLimestoneCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkLimestoneCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkLimestoneCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkLimestoneCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkLimestoneCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkLimestoneCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkLimestoneCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkJasperCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkJasperCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkJasperCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkJasperCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkJasperCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkJasperCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkJasperCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkJasperCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkJasperCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkMarbleCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkMarbleCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkMarbleCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkMarbleCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkMarbleCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkMarbleCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkMarbleCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkMarbleCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkMarbleCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkSlateCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkSlateCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkSlateCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkSlateCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkSlateCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkSlateCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkSlateCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkSlateCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkSlateCobaltOre;

    // Embellishcraft
    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftBasaltCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftBasaltCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftBasaltCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftBasaltCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftBasaltCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftBasaltCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftBasaltCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftBasaltCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftBasaltCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftGneissCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftGneissCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftGneissCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftGneissCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftGneissCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftGneissCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftGneissCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftGneissCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftGneissCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftJadeCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftJadeCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftJadeCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftJadeCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftJadeCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftJadeCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftJadeCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftJadeCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftJadeCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftMarbleCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftMarbleCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftMarbleCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftMarbleCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftMarbleCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftMarbleCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftMarbleCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftMarbleCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftMarbleCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftLarvikiteCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftLarvikiteCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftLarvikiteCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftLarvikiteCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftLarvikiteCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftLarvikiteCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftLarvikiteCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftLarvikiteCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftLarvikiteCobaltOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftSlateCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftSlateCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftSlateCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftSlateCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftSlateCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftSlateCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftSlateCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftSlateCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftSlateCobaltOre;

    // Danny's Stone Variants
    public static ForgeConfigSpec.BooleanValue enableHardenedStoneCobaltOre;
    public static ForgeConfigSpec.IntValue veinSizeHardenedStoneCobaltOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkHardenedStoneCobaltOre;
    public static ForgeConfigSpec.IntValue minHeightHardenedStoneCobaltOre;
    public static ForgeConfigSpec.IntValue maxHeightHardenedStoneCobaltOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistHardenedStoneCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistHardenedStoneCobaltOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistHardenedStoneCobaltOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistHardenedStoneCobaltOre;

    static {
        // = BUILDER.comment("").define("", false);

        BUILDER.comment("Cobalt Ores").push("general");
        disableCobaltOres = BUILDER.comment("If false, all cobalt ore variants will be disabled.").define("disableAllVariants", false);
        BUILDER.comment("Stone Cobalt Ore").push("stone_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableStoneCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeStoneCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkStoneCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightStoneCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightStoneCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistStoneCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistStoneCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistStoneCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistStoneCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Andesite Cobalt Ore").push("andesite_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableAndesiteCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeAndesiteCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkAndesiteCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightAndesiteCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightAndesiteCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistAndesiteCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistAndesiteCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistAndesiteCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistAndesiteCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Diorite Cobalt Ore").push("diorite_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableDioriteCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeDioriteCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkDioriteCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightDioriteCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightDioriteCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistDioriteCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistDioriteCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistDioriteCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistDioriteCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Granite Cobalt Ore").push("granite_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableGraniteCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeGraniteCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkGraniteCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightGraniteCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightGraniteCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistGraniteCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistGraniteCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistGraniteCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistGraniteCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Netherrack Cobalt Ore").push("netherrack_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableNetherrackCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeNetherrackCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkNetherrackCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightNetherrackCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 96, 0, 256);
        maxHeightNetherrackCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistNetherrackCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistNetherrackCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistNetherrackCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistNetherrackCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("End Stone Cobalt Ore").push("end_stone_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEndStoneCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEndStoneCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkEndStoneCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightEndStoneCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEndStoneCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 32, 0, 256);
        isTempWhitelistEndStoneCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEndStoneCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEndStoneCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEndStoneCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Sand Cobalt Ore").push("sand_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableSandCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeSandCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 3, 0, 65536);
        veinsPerChunkSandCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightSandCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightSandCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistSandCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistSandCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistSandCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistSandCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Red Sand Cobalt Ore").push("red_sand_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableRedSandCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeRedSandCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 3, 0, 65536);
        veinsPerChunkRedSandCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightRedSandCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightRedSandCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistRedSandCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistRedSandCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistRedSandCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistRedSandCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Gravel Cobalt Ore").push("gravel_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableGravelCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeGravelCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 3, 0, 65536);
        veinsPerChunkGravelCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightGravelCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightGravelCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistGravelCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistGravelCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistGravelCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistGravelCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Sandstone Cobalt Ore").push("sandstone_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableSandstoneCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeSandstoneCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 3, 0, 65536);
        veinsPerChunkSandstoneCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightSandstoneCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightSandstoneCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistSandstoneCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistSandstoneCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistSandstoneCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistSandstoneCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Red Sandstone Cobalt Ore").push("red_sandstone_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableRedSandstoneCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeRedSandstoneCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 3, 0, 65536);
        veinsPerChunkRedSandstoneCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightRedSandstoneCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightRedSandstoneCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistRedSandstoneCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistRedSandstoneCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistRedSandstoneCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistRedSandstoneCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Blue Ice Cobalt Ore").push("blue_ice_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableBlueIceCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeBlueIceCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 3, 0, 65536);
        veinsPerChunkBlueIceCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightBlueIceCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightBlueIceCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistBlueIceCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistBlueIceCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistBlueIceCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistBlueIceCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Packed Ice Cobalt Ore").push("packed_ice_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enablePackedIceCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizePackedIceCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 3, 0, 65536);
        veinsPerChunkPackedIceCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightPackedIceCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightPackedIceCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistPackedIceCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistPackedIceCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistPackedIceCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistPackedIceCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Bedrock Cobalt Ore").push("bedrock_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableBedrockCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeBedrockCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkBedrockCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 1, 0, 65536);
        minHeightBedrockCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightBedrockCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 256, 0, 256);
        isTempWhitelistBedrockCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistBedrockCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistBedrockCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistBedrockCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.comment("Block properties").push("properties");
        resistanceBedrockCobaltOre = BUILDER.comment("A higher value means a stronger explosion is needed to destroy this ore. Stone has 6.0 and Obsidian 1200.0").defineInRange("resistance", 9.0, 0.0, 3600000.0);
        BUILDER.pop();
        BUILDER.pop();

        //Quark
        BUILDER.comment("Basalt Cobalt Ore (Quark)").push("quark_basalt_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkBasaltCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeQuarkBasaltCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkQuarkBasaltCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightQuarkBasaltCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 96, 0, 256);
        maxHeightQuarkBasaltCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistQuarkBasaltCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistQuarkBasaltCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistQuarkBasaltCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistQuarkBasaltCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Limestone Cobalt Ore (Quark)").push("quark_limestone_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkLimestoneCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeQuarkLimestoneCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkQuarkLimestoneCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightQuarkLimestoneCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightQuarkLimestoneCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistQuarkLimestoneCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistQuarkLimestoneCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistQuarkLimestoneCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistQuarkLimestoneCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Jasper Cobalt Ore (Quark)").push("quark_jasper_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkJasperCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeQuarkJasperCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkQuarkJasperCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightQuarkJasperCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightQuarkJasperCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistQuarkJasperCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistQuarkJasperCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistQuarkJasperCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistQuarkJasperCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Marble Cobalt Ore (Quark)").push("quark_marble_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkMarbleCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeQuarkMarbleCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkQuarkMarbleCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightQuarkMarbleCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightQuarkMarbleCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistQuarkMarbleCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistQuarkMarbleCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistQuarkMarbleCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistQuarkMarbleCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Slate Cobalt Ore (Quark)").push("quark_slate_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkSlateCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeQuarkSlateCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkQuarkSlateCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightQuarkSlateCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightQuarkSlateCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistQuarkSlateCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistQuarkSlateCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistQuarkSlateCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistQuarkSlateCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();

        //Embellishcraft
        BUILDER.comment("Basalt Cobalt Ore (Embellishcraft)").push("embellishcraft_basalt_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftBasaltCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftBasaltCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkEmbellishcraftBasaltCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightEmbellishcraftBasaltCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftBasaltCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistEmbellishcraftBasaltCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftBasaltCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftBasaltCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftBasaltCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Gneiss Cobalt Ore (Embellishcraft)").push("embellishcraft_gneiss_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftGneissCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftGneissCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkEmbellishcraftGneissCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightEmbellishcraftGneissCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftGneissCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistEmbellishcraftGneissCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftGneissCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftGneissCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftGneissCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Jade Cobalt Ore (Embellishcraft)").push("embellishcraft_jade_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftJadeCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftJadeCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkEmbellishcraftJadeCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightEmbellishcraftJadeCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftJadeCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistEmbellishcraftJadeCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftJadeCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftJadeCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftJadeCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Larvikite Cobalt Ore (Embellishcraft)").push("embellishcraft_larvikite_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftLarvikiteCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftLarvikiteCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkEmbellishcraftLarvikiteCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightEmbellishcraftLarvikiteCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftLarvikiteCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistEmbellishcraftLarvikiteCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftLarvikiteCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftLarvikiteCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftLarvikiteCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Marble Cobalt Ore (Embellishcraft)").push("embellishcraft_marble_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftMarbleCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftMarbleCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkEmbellishcraftMarbleCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightEmbellishcraftMarbleCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftMarbleCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistEmbellishcraftMarbleCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftMarbleCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftMarbleCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftMarbleCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Slate Cobalt Ore (Embellishcraft)").push("embellishcraft_slate_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftSlateCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftSlateCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkEmbellishcraftSlateCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightEmbellishcraftSlateCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftSlateCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistEmbellishcraftSlateCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftSlateCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftSlateCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftSlateCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();

        // Danny's Stone Variants
        BUILDER.comment("Hardened Stone Cobalt Ore").push("hardened_stone_cobalt_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableHardenedStoneCobaltOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeHardenedStoneCobaltOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 6, 0, 65536);
        veinsPerChunkHardenedStoneCobaltOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 2, 0, 65536);
        minHeightHardenedStoneCobaltOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightHardenedStoneCobaltOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 16, 0, 256);
        isTempWhitelistHardenedStoneCobaltOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistHardenedStoneCobaltOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistHardenedStoneCobaltOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistHardenedStoneCobaltOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:meadow\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.pop();
        spec = BUILDER.build();
        //BUILDER.comment("").push("");
        //
        //BUILDER.pop();
    }

    public static void loadConfig() {
        ModLoadingContext.get().registerConfig(ModConfig.Type.COMMON, Cobalt.spec, Main.MOD_ID + "/cobalt.toml");
    }
}
