package com.danny.dannys_ores.configs.ores;

import com.danny.dannys_ores.Main;
import net.minecraftforge.common.ForgeConfigSpec;
import net.minecraftforge.fml.ModLoadingContext;
import net.minecraftforge.fml.config.ModConfig;

import java.util.ArrayList;
import java.util.List;

public class Lead {
    private static final ForgeConfigSpec.Builder BUILDER = new ForgeConfigSpec.Builder();
    public static ForgeConfigSpec spec;
    public static ForgeConfigSpec.BooleanValue disableLeadOres;

    public static ForgeConfigSpec.BooleanValue enableStoneLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeStoneLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkStoneLeadOre;
    public static ForgeConfigSpec.IntValue minHeightStoneLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightStoneLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistStoneLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistStoneLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistStoneLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistStoneLeadOre;

    public static ForgeConfigSpec.BooleanValue enableAndesiteLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeAndesiteLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkAndesiteLeadOre;
    public static ForgeConfigSpec.IntValue minHeightAndesiteLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightAndesiteLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistAndesiteLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistAndesiteLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistAndesiteLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistAndesiteLeadOre;

    public static ForgeConfigSpec.BooleanValue enableDioriteLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeDioriteLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkDioriteLeadOre;
    public static ForgeConfigSpec.IntValue minHeightDioriteLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightDioriteLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistDioriteLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistDioriteLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistDioriteLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistDioriteLeadOre;

    public static ForgeConfigSpec.BooleanValue enableGraniteLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeGraniteLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkGraniteLeadOre;
    public static ForgeConfigSpec.IntValue minHeightGraniteLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightGraniteLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistGraniteLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistGraniteLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistGraniteLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistGraniteLeadOre;

    public static ForgeConfigSpec.BooleanValue enableNetherrackLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeNetherrackLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkNetherrackLeadOre;
    public static ForgeConfigSpec.IntValue minHeightNetherrackLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightNetherrackLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistNetherrackLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistNetherrackLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistNetherrackLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistNetherrackLeadOre;

    public static ForgeConfigSpec.BooleanValue enableEndStoneLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeEndStoneLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEndStoneLeadOre;
    public static ForgeConfigSpec.IntValue minHeightEndStoneLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightEndStoneLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEndStoneLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEndStoneLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEndStoneLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEndStoneLeadOre;

    public static ForgeConfigSpec.BooleanValue enableSandLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeSandLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkSandLeadOre;
    public static ForgeConfigSpec.IntValue minHeightSandLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightSandLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistSandLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistSandLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistSandLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistSandLeadOre;

    public static ForgeConfigSpec.BooleanValue enableRedSandLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeRedSandLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkRedSandLeadOre;
    public static ForgeConfigSpec.IntValue minHeightRedSandLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightRedSandLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistRedSandLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistRedSandLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistRedSandLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistRedSandLeadOre;

    public static ForgeConfigSpec.BooleanValue enableGravelLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeGravelLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkGravelLeadOre;
    public static ForgeConfigSpec.IntValue minHeightGravelLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightGravelLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistGravelLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistGravelLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistGravelLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistGravelLeadOre;

    public static ForgeConfigSpec.BooleanValue enableSandstoneLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeSandstoneLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkSandstoneLeadOre;
    public static ForgeConfigSpec.IntValue minHeightSandstoneLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightSandstoneLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistSandstoneLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistSandstoneLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistSandstoneLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistSandstoneLeadOre;

    public static ForgeConfigSpec.BooleanValue enableRedSandstoneLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeRedSandstoneLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkRedSandstoneLeadOre;
    public static ForgeConfigSpec.IntValue minHeightRedSandstoneLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightRedSandstoneLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistRedSandstoneLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistRedSandstoneLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistRedSandstoneLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistRedSandstoneLeadOre;

    public static ForgeConfigSpec.BooleanValue enableBlueIceLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeBlueIceLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkBlueIceLeadOre;
    public static ForgeConfigSpec.IntValue minHeightBlueIceLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightBlueIceLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistBlueIceLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistBlueIceLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistBlueIceLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistBlueIceLeadOre;

    public static ForgeConfigSpec.BooleanValue enablePackedIceLeadOre;
    public static ForgeConfigSpec.IntValue veinSizePackedIceLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkPackedIceLeadOre;
    public static ForgeConfigSpec.IntValue minHeightPackedIceLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightPackedIceLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistPackedIceLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistPackedIceLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistPackedIceLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistPackedIceLeadOre;

    public static ForgeConfigSpec.BooleanValue enableBedrockLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeBedrockLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkBedrockLeadOre;
    public static ForgeConfigSpec.IntValue minHeightBedrockLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightBedrockLeadOre;
    public static ForgeConfigSpec.DoubleValue resistanceBedrockLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistBedrockLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistBedrockLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistBedrockLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistBedrockLeadOre;

    // Quark
    public static ForgeConfigSpec.BooleanValue enableQuarkBasaltLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkBasaltLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkBasaltLeadOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkBasaltLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkBasaltLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkBasaltLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkBasaltLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkBasaltLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkBasaltLeadOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkLimestoneLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkLimestoneLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkLimestoneLeadOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkLimestoneLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkLimestoneLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkLimestoneLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkLimestoneLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkLimestoneLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkLimestoneLeadOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkJasperLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkJasperLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkJasperLeadOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkJasperLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkJasperLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkJasperLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkJasperLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkJasperLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkJasperLeadOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkMarbleLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkMarbleLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkMarbleLeadOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkMarbleLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkMarbleLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkMarbleLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkMarbleLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkMarbleLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkMarbleLeadOre;

    public static ForgeConfigSpec.BooleanValue enableQuarkSlateLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeQuarkSlateLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkQuarkSlateLeadOre;
    public static ForgeConfigSpec.IntValue minHeightQuarkSlateLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightQuarkSlateLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistQuarkSlateLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistQuarkSlateLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistQuarkSlateLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistQuarkSlateLeadOre;

    // Embellishcraft
    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftBasaltLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftBasaltLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftBasaltLeadOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftBasaltLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftBasaltLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftBasaltLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftBasaltLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftBasaltLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftBasaltLeadOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftGneissLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftGneissLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftGneissLeadOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftGneissLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftGneissLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftGneissLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftGneissLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftGneissLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftGneissLeadOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftJadeLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftJadeLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftJadeLeadOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftJadeLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftJadeLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftJadeLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftJadeLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftJadeLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftJadeLeadOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftMarbleLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftMarbleLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftMarbleLeadOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftMarbleLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftMarbleLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftMarbleLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftMarbleLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftMarbleLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftMarbleLeadOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftLarvikiteLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftLarvikiteLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftLarvikiteLeadOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftLarvikiteLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftLarvikiteLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftLarvikiteLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftLarvikiteLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftLarvikiteLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftLarvikiteLeadOre;

    public static ForgeConfigSpec.BooleanValue enableEmbellishcraftSlateLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeEmbellishcraftSlateLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkEmbellishcraftSlateLeadOre;
    public static ForgeConfigSpec.IntValue minHeightEmbellishcraftSlateLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightEmbellishcraftSlateLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistEmbellishcraftSlateLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistEmbellishcraftSlateLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistEmbellishcraftSlateLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistEmbellishcraftSlateLeadOre;

    // Danny's Stone Variants
    public static ForgeConfigSpec.BooleanValue enableHardenedStoneLeadOre;
    public static ForgeConfigSpec.IntValue veinSizeHardenedStoneLeadOre;
    public static ForgeConfigSpec.IntValue veinsPerChunkHardenedStoneLeadOre;
    public static ForgeConfigSpec.IntValue minHeightHardenedStoneLeadOre;
    public static ForgeConfigSpec.IntValue maxHeightHardenedStoneLeadOre;
    public static ForgeConfigSpec.BooleanValue isTempWhitelistHardenedStoneLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> temperatureBlacklistHardenedStoneLeadOre;
    public static ForgeConfigSpec.BooleanValue isBiomeWhitelistHardenedStoneLeadOre;
    public static ForgeConfigSpec.ConfigValue<List<String>> biomeBlacklistHardenedStoneLeadOre;

    static {
        // = BUILDER.comment("").define("", false);

        BUILDER.comment("Lead Ores").push("general");
        disableLeadOres = BUILDER.comment("If false, all lead ore variants will be disabled.").define("disableAllVariants", false);
        BUILDER.comment("Stone Lead Ore").push("stone_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableStoneLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeStoneLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkStoneLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightStoneLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightStoneLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 40, 0, 256);
        isTempWhitelistStoneLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistStoneLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistStoneLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistStoneLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Andesite Lead Ore").push("andesite_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableAndesiteLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeAndesiteLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkAndesiteLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightAndesiteLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightAndesiteLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 40, 0, 256);
        isTempWhitelistAndesiteLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistAndesiteLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistAndesiteLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistAndesiteLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Diorite Lead Ore").push("diorite_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableDioriteLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeDioriteLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkDioriteLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightDioriteLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightDioriteLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 40, 0, 256);
        isTempWhitelistDioriteLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistDioriteLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistDioriteLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistDioriteLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Granite Lead Ore").push("granite_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableGraniteLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeGraniteLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkGraniteLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightGraniteLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightGraniteLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 40, 0, 256);
        isTempWhitelistGraniteLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistGraniteLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistGraniteLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistGraniteLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Netherrack Lead Ore").push("netherrack_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableNetherrackLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeNetherrackLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkNetherrackLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightNetherrackLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 10, 0, 256);
        maxHeightNetherrackLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 96, 0, 256);
        isTempWhitelistNetherrackLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistNetherrackLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistNetherrackLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistNetherrackLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("End Stone Lead Ore").push("end_stone_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEndStoneLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEndStoneLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkEndStoneLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightEndStoneLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 60, 0, 256);
        maxHeightEndStoneLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistEndStoneLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEndStoneLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEndStoneLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEndStoneLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Sand Lead Ore").push("sand_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableSandLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeSandLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkSandLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightSandLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightSandLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistSandLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistSandLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistSandLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistSandLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Red Sand Lead Ore").push("red_sand_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableRedSandLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeRedSandLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkRedSandLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightRedSandLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightRedSandLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistRedSandLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistRedSandLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistRedSandLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistRedSandLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Gravel Lead Ore").push("gravel_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableGravelLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeGravelLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkGravelLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightGravelLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightGravelLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistGravelLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistGravelLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistGravelLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistGravelLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Sandstone Lead Ore").push("sandstone_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableSandstoneLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeSandstoneLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkSandstoneLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightSandstoneLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightSandstoneLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistSandstoneLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistSandstoneLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistSandstoneLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistSandstoneLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Red Sandstone Lead Ore").push("red_sandstone_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableRedSandstoneLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeRedSandstoneLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkRedSandstoneLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightRedSandstoneLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightRedSandstoneLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistRedSandstoneLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistRedSandstoneLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistRedSandstoneLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistRedSandstoneLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Blue Ice Lead Ore").push("blue_ice_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableBlueIceLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeBlueIceLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkBlueIceLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightBlueIceLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightBlueIceLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistBlueIceLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistBlueIceLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistBlueIceLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistBlueIceLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Packed Ice Lead Ore").push("packed_ice_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enablePackedIceLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizePackedIceLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkPackedIceLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightPackedIceLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightPackedIceLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 128, 0, 256);
        isTempWhitelistPackedIceLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistPackedIceLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistPackedIceLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistPackedIceLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Bedrock Lead Ore").push("bedrock_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableBedrockLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeBedrockLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 1, 0, 65536);
        veinsPerChunkBedrockLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 1, 0, 65536);
        minHeightBedrockLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightBedrockLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 256, 0, 256);
        isTempWhitelistBedrockLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistBedrockLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistBedrockLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistBedrockLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.comment("Block properties").push("properties");
        resistanceBedrockLeadOre = BUILDER.comment("A higher value means a stronger explosion is needed to destroy this ore. Stone has 6.0 and Obsidian 1200.0").defineInRange("resistance", 9.0, 0.0, 3600000.0);
        BUILDER.pop();
        BUILDER.pop();

        //Quark
        BUILDER.comment("Basalt Lead Ore (Quark)").push("quark_basalt_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkBasaltLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeQuarkBasaltLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkQuarkBasaltLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightQuarkBasaltLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 10, 0, 256);
        maxHeightQuarkBasaltLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 96, 0, 256);
        isTempWhitelistQuarkBasaltLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistQuarkBasaltLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistQuarkBasaltLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistQuarkBasaltLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Limestone Lead Ore (Quark)").push("quark_limestone_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkLimestoneLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeQuarkLimestoneLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkQuarkLimestoneLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightQuarkLimestoneLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightQuarkLimestoneLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 40, 0, 256);
        isTempWhitelistQuarkLimestoneLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistQuarkLimestoneLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistQuarkLimestoneLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistQuarkLimestoneLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Jasper Lead Ore (Quark)").push("quark_jasper_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkJasperLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeQuarkJasperLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkQuarkJasperLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightQuarkJasperLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightQuarkJasperLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 40, 0, 256);
        isTempWhitelistQuarkJasperLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistQuarkJasperLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistQuarkJasperLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistQuarkJasperLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Marble Lead Ore (Quark)").push("quark_marble_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkMarbleLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeQuarkMarbleLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkQuarkMarbleLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightQuarkMarbleLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightQuarkMarbleLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 40, 0, 256);
        isTempWhitelistQuarkMarbleLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistQuarkMarbleLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistQuarkMarbleLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistQuarkMarbleLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Slate Lead Ore (Quark)").push("quark_slate_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableQuarkSlateLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeQuarkSlateLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkQuarkSlateLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightQuarkSlateLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightQuarkSlateLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 40, 0, 256);
        isTempWhitelistQuarkSlateLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistQuarkSlateLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistQuarkSlateLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistQuarkSlateLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();

        //Embellishcraft
        BUILDER.comment("Basalt Lead Ore (Embellishcraft)").push("embellishcraft_basalt_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftBasaltLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftBasaltLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkEmbellishcraftBasaltLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightEmbellishcraftBasaltLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftBasaltLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 40, 0, 256);
        isTempWhitelistEmbellishcraftBasaltLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftBasaltLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftBasaltLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftBasaltLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Gneiss Lead Ore (Embellishcraft)").push("embellishcraft_gneiss_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftGneissLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftGneissLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkEmbellishcraftGneissLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightEmbellishcraftGneissLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftGneissLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 40, 0, 256);
        isTempWhitelistEmbellishcraftGneissLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftGneissLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftGneissLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftGneissLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Jade Lead Ore (Embellishcraft)").push("embellishcraft_jade_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftJadeLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftJadeLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkEmbellishcraftJadeLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightEmbellishcraftJadeLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftJadeLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 40, 0, 256);
        isTempWhitelistEmbellishcraftJadeLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftJadeLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftJadeLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftJadeLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Larvikite Lead Ore (Embellishcraft)").push("embellishcraft_larvikite_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftLarvikiteLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftLarvikiteLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkEmbellishcraftLarvikiteLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightEmbellishcraftLarvikiteLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftLarvikiteLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 40, 0, 256);
        isTempWhitelistEmbellishcraftLarvikiteLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftLarvikiteLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftLarvikiteLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftLarvikiteLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Marble Lead Ore (Embellishcraft)").push("embellishcraft_marble_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftMarbleLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftMarbleLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkEmbellishcraftMarbleLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightEmbellishcraftMarbleLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftMarbleLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 40, 0, 256);
        isTempWhitelistEmbellishcraftMarbleLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftMarbleLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftMarbleLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftMarbleLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.comment("Slate Lead Ore (Embellishcraft)").push("embellishcraft_slate_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableEmbellishcraftSlateLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeEmbellishcraftSlateLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkEmbellishcraftSlateLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightEmbellishcraftSlateLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightEmbellishcraftSlateLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 40, 0, 256);
        isTempWhitelistEmbellishcraftSlateLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistEmbellishcraftSlateLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistEmbellishcraftSlateLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistEmbellishcraftSlateLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        // Danny's Stone Variants
        BUILDER.comment("Hardened Stone Lead Ore").push("hardened_stone_lead_ore");
        BUILDER.comment("Generation settings for this ore.").push("generation");
        enableHardenedStoneLeadOre = BUILDER.comment("If false, this ore variant will not generate.").define("enableVariant", true);
        veinSizeHardenedStoneLeadOre = BUILDER.comment("The amount of ores in one vein.").defineInRange("veinSize", 4, 0, 65536);
        veinsPerChunkHardenedStoneLeadOre = BUILDER.comment("How many veins per chunk.").defineInRange("veinsPerChunk", 4, 0, 65536);
        minHeightHardenedStoneLeadOre = BUILDER.comment("The min y-level the ore will generate.").defineInRange("minHeight", 0, 0, 256);
        maxHeightHardenedStoneLeadOre = BUILDER.comment("The max y-level the ore will generate.").defineInRange("maxHeight", 40, 0, 256);
        isTempWhitelistHardenedStoneLeadOre = BUILDER.comment("If true, the biome temperature blacklist is a whitelist.").define("isTempWhitelist", false);
        temperatureBlacklistHardenedStoneLeadOre = BUILDER.comment("Possible Entries: \"MEDIUM\", \"WARM\", \"COLD\", \"OCEAN\"").define("temperatureBlacklist", new ArrayList<String>());
        isBiomeWhitelistHardenedStoneLeadOre = BUILDER.comment("If true, the biome blacklist is a whitelist.").define("isBiomeWhitelist", false);
        biomeBlacklistHardenedStoneLeadOre = BUILDER.comment("Syntax: \"modid:biome\". E.g.: [\"minecraft:plains\", \"biomesoplenty:alps\"])").define("biomeBlacklist", new ArrayList<String>());
        BUILDER.pop();
        BUILDER.pop();
        BUILDER.pop();
        spec = BUILDER.build();
        //BUILDER.comment("").push("");
        //
        //BUILDER.pop();
    }

    public static void loadConfig() {
        ModLoadingContext.get().registerConfig(ModConfig.Type.COMMON, Lead.spec, Main.MOD_ID + "/lead.toml");
    }
}
